### PR TITLE
Fixed empty plots and added automatic log out when token is not valid

### LINKED ISSUE #79: Float series flush all their nodes when they are rendered in a different place
The float series card flushes its nodes when its content is rendered in a different place of the UI (e.g. when the user switches from mobile to desktop or when the tile is opened in full screen mode).

### PR DESCRIPTION
**Pull request by SamueleDassatti**
The float series card doesn't flush anymore all of its data when it's re-rendered (closes #79) and the user is forced to log out if their token is invalid or expired.

### CODE REVIEW

File: src/components/MainBody.js [hunk 1]
```diff
@@ -283,7 +283,7 @@ export default class MainBody extends Component {
     }
 
     if (error) {
-      if (error.message === "GraphQL error: This user doesn't exist anymore") {
+      if (error.message === "GraphQL error: This user doesn't exist anymore" || error.message === "Network error: Response not successful: Received status code 401") {
```
Comment (ZaninAndrea) [inline src/components/MainBody.js]: Token expired error should be handler at top level in Apollo's HTTPLink and WebSocketLink

File: src/components/settings/VerifyAuthentication.js [hunk 2]
```diff
@@ -194,7 +194,11 @@ export default class VerifyAuthentication extends Component {
       nextProps.open !== this.props.open &&
       nextProps.open &&
       this.props.user &&
-      !this.props.user.primaryAuthenticationMethods[0]
+      (!this.props.user.primaryAuthenticationMethods[0] ||
```
Comment (ZaninAndrea) [inline src/components/settings/VerifyAuthentication.js]: Is there a reason to use `JSON.stringify(this.props.user.primaryAuthenticationMethods) === '["WEBAUTHN"]'` instead of the more standard approach `this.props.user.primaryAuthenticationMethods.length === 1 && this.props.user.primaryAuthenticationMethods[0] === "WEBAUTHN"`?

For a more compact notation you could also use the `deep-equal` package: `deepEqual(this.props.user.primaryAuthenticationMethods, ["WEBAUTHN"])`

Comment (SamueleDassatti) [reply src/components/settings/VerifyAuthentication.js]: There isn't a specific reason, switching to deep equality check soon.

**Comment by SamueleDassatti** [comment]
This pull request **introduces 1 alert** and **fixes 12** when merging c173dd656a05ed18cd2fee5ae5e360b43878198f into bd7a55149eede41a745818b20676d2363c1dddd3 - [view on LGTM.com](https://lgtm.com/projects/g/IglooCloud/IglooAurora/rev/pr-8960b93e0ae89fca578f9e9cbebf695846e5e673)

**new alerts:**

* 1 for Unused or undefined state property

**fixed alerts:**

* 11 for Useless conditional
* 1 for Unused or undefined state property

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by SamueleDassatti** [comment]
This pull request **introduces 1 alert** and **fixes 12** when merging 9896248f13dfa0807d7c95b4b185dcd28bf3a6a9 into bd7a55149eede41a745818b20676d2363c1dddd3 - [view on LGTM.com](https://lgtm.com/projects/g/IglooCloud/IglooAurora/rev/pr-88f8d6d2bc162a37c6a4433a2aaecf6f8107a306)

**new alerts:**

* 1 for Unused or undefined state property

**fixed alerts:**

* 11 for Useless conditional
* 1 for Unused or undefined state property

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by SamueleDassatti** [comment]
This pull request **introduces 1 alert** and **fixes 12** when merging f41d1989e44896372f0c59ed54f5ea038156e198 into bd7a55149eede41a745818b20676d2363c1dddd3 - [view on LGTM.com](https://lgtm.com/projects/g/IglooCloud/IglooAurora/rev/pr-0de8528bd19fe7afd9805bec9a62af0d73b73a03)

**new alerts:**

* 1 for Unused or undefined state property

**fixed alerts:**

* 11 for Useless conditional
* 1 for Unused or undefined state property

---

*Comment posted by [LGTM.com](https://lgtm.com)*
